### ISSUE TITLE
Query on open-sourcing plans for your exceptional work

### ISSUE THREAD

**Issue by Amuseum-WHR** [astra-vision/MaterialPalette#1]
Hello, I'm a student from SJTU. I'm deeply impressed by your exceptional work on materials. I wonder if you have any plans to release the source code as open-source in the future and I am really looking forward to it.

**Comment by wonjunior** [comment]
Hi @Amuseum-WHR, thank you for your interest in our work! We will make the project open-source and available for you to test very soon. Stay tuned for new updates on the repository and web page.

**Comment by Amuseum-WHR** [comment]
Hi, how soon will this project be open-source and available? Maybe you can provide a rough timeline?

> Hi @Amuseum-WHR, thank you for your interest in our work! We will make the project open-source and available for you to test very soon. Stay tuned for new updates on the repository and web page.

**Comment by telee9527** [comment]
I kindly request the release of the source code as it would greatly benefit my research. Your code is invaluable to my studies. Thank you in advance for considering my request!

**Comment by snowflakewang** [comment]
> Hi again, I appreciate your excitement @Amuseum-WHR! A first code release should be pushed by the end of next week.

Hello, Thank you for your brilliant work on Stable Diffusion-based material estimation/generation! I am curious about your dataset _**TexSD**_. Will _**TexSD**_ be released together with the code at the same time?

Thank you! :)

**Comment by vararth** [comment]
Also here wondering what the license terms for this project implementation will be! Looking forward to being able to experiment on these functionalities!

**Comment by wonjunior** [comment]
Thank you all for your interest and enthusiasm. The code has been released tonight.
I apologize for the inaccurate release time estimation; the project took longer than anticipated. 
@snowflakewang, **_TexSD_** will be released at a later stage as it didn't make it in time with the code. 
@vararth, we have chosen the MIT license for this repository.
