### ISSUE TITLE
stable-diffusion-v1-5 inaccessible

### ISSUE THREAD

**Issue by ZheningHuang** [astra-vision/MaterialPalette#12]
Hi,
Thanks again for this great work!
I'm encountering an issue when trying to use the code. Here’s the error message I receive:
```
loading LoRA with token azertyuiop
Couldn't connect to the Hub: 404 Client Error. (Request ID: Root=1-66e985f5-3f86e6850e6230a815cd36fb;a533c066-f43a-4967-9ddb-9fac036937e0)

Repository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5.

```

stable-diffusion-v1-5 is inaccessible now. Is there an alternative plan for this? 
Thanks a lot for your help!

**Comment by wonjunior** [comment]
Hi Zhening, I wasn't aware Runaway took down the v1.5 models, thanks for pointing it out here! It appears some users made these weights available again via HuggingFace, [see here](https://www.reddit.com/r/StableDiffusion/comments/1f4epto/runway_took_down_15_and_15_inpainting/). If you replace the path in our code, it will work fine. Also if you want to try out a different version of SD, you can for example use [SDv2 from StabilityAI](https://huggingface.co/stabilityai/stable-diffusion-2), I remember trying it out. I hope this helps you!

**Comment by ZheningHuang** [comment]
Thanks a lot, I used `https://huggingface.co/benjamin-paine/stable-diffusion-v1-5` and it works fine now!
