### ISSUE TITLE
the configuration file in training

### ISSUE THREAD

**Issue by zhang0227** [astra-vision/MaterialPalette#13]
Thank you for sharing this project on GitHub; it's been really helpful! I'm currently trying to retrain on the same datasets and was wondering if you could share an example yml configuration file.

**Comment by wonjunior** [comment]
Hi, thanks for your interest in the repository! 
Sure thing, the decomposition training follows a two-step process. First, we pre-train 1k epochs on AmbientCG (the source dataset) with this [config](https://gist.github.com/wonjunior/6a20b9f26fb1c76fc69ee0c65f5994de), then proceed with finetuning the network for a further 100 epochs on AmbientCG and TexSD (source and target datasets) with this [config](https://gist.github.com/wonjunior/1594fd5d9a46fd2e279ba861a448212d). Feel free to check section A.2 of the [supplementary material](https://openaccess.thecvf.com/content/CVPR2024/supplemental/Lopes_Material_Palette_Extraction_CVPR_2024_supplemental.pdf) for more details on this part of the method.
That should get you started, good luck with your work!

**Comment by zhang0227** [comment]
Thank you for your help! The issue is resolved, and your answer was very helpful. I will go ahead and close this issue now.
