### ISSUE TITLE
Assertion Error when starting decomposition using Pipeline.py

### ISSUE THREAD

**Issue by Sagnik2810Sarkar** [astra-vision/MaterialPalette#5]
I got the following error when trying the mansion.zip pipeline example provided in the readme.

Traceback (most recent call last):
  File "G:\SAGNIK_Material_Palette\Material_Palette\MaterialPalette\pipeline.py", line 25, in <module>
    module = capture.get_inference_module(pt='model.ckpt')
  File "G:\SAGNIK_Material_Palette\Material_Palette\MaterialPalette\capture\utils\model.py", line 41, in get_inference_module
    assert Path(pt).exists()
AssertionError

I cant figure out what the model.ckpt is supposed to be referencing because there is no ckpt file in the capture directory itself.

**Comment by wonjunior** [comment]
Hi @Sagnik2810Sarkar, did you download the model checkpoint from [here](https://github.com/astra-vision/MaterialPalette/releases/download/weights/model.tar.gz)?

**Comment by Sagnik2810Sarkar** [comment]
Sorry for the late reply, but yeah the model file actually downloaded in the wrong folder. Due to some hardware constraints further attempts at decomposition keep getting interrupted so I'll post an update as soon as it works or I get stuck somewhere else.

**Comment by wonjunior** [comment]
There are no logs from Lightning, the outputs should be located in the same directory as the LoRA checkpoint. For example, the outputs of the grass region in the `mansion` example will be in  
```
mansion\weights\grass\an_object_with_azertyuiop_texture\checkpoint-800
```
There, you will find a `outputs` directory - and if `renorm` is enabled - a `out_renorm` directory.

**Comment by Sagnik2810Sarkar** [comment]
Got it, I thought the outputs for decomposition would be in a separate folder so I didn't check these.

**Comment by wonjunior** [comment]
I will close this issue for now but don't hesitate to come back to me if you need more assistance.
