### ISSUE TITLE
how can I test my single img use pipeline.py

### ISSUE THREAD

**Issue by Qiuhao-Wu** [astra-vision/MaterialPalette#9]
hello,  the following is my structure:
![企业微信截图_17225949167199](https://github.com/user-attachments/assets/471243d4-a4c8-4bd7-aafe-d25528283399)
I put only one single portrait img at the directory img.
I modify the code at pipeline.py, I only need to test your model.ckpt, decopose the A N R .
![企业微信截图_17225950507884](https://github.com/user-attachments/assets/db805c61-ca68-4ac9-aabc-fdedddb30525)
=============================================
I think I need your help, meet the following problem:
![Uploading 企业微信截图_17225951578875.png…]()

**Comment by Qiuhao-Wu** [comment]
![企业微信截图_17225951578875](https://github.com/user-attachments/assets/5784148c-7215-4704-9b68-30f37350afdc)

**Comment by Qiuhao-Wu** [comment]
> The dataloader expects a certain directory structure and filename pattern in order to work seamlessly with the texture extraction step. You can refer to this [line](https://github.com/astra-vision/MaterialPalette/blob/master/capture/data/target.py#L37). In your case, the captures you are testing on should be located inside a "outputs" path. I recommend you try out the examples from the readme file, that way you can get a feel of how the pipeline runs. I hope this clarifies your concerns!

========================================================
Thanks  for  your help, I work it.
I test the model on potrait img, however, the result is not satisfy me .
Maybe the model havenot seen the potrait data.
I think your work give us a good reference.
I will use the OLAT data to train.

**Comment by wonjunior** [comment]
It is very likely, indeed our model was not trained on portrait images, only texture images!
